// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzaSQnF3pziQ114Z6LX8fNq1HWZCOOqeY',
    appId: '1:375709920710:web:09c939873888d6bfed16c7',
    messagingSenderId: '375709920710',
    projectId: 'flutter-english-d72fb',
    authDomain: 'flutter-english-d72fb.firebaseapp.com',
    storageBucket: 'flutter-english-d72fb.appspot.com',
    measurementId: 'G-4XWRM94E32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHlZFPoGn5tvqRmOAXvPKppkodrZTD54',
    appId: '1:375709920710:android:9ea9eb50f357768eed16c7',
    messagingSenderId: '375709920710',
    projectId: 'flutter-english-d72fb',
    storageBucket: 'flutter-english-d72fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV5-RRqUd2_5wzwCYLKRpXMJDD5seWI-s',
    appId: '1:375709920710:ios:2b2c2722dc6436b6ed16c7',
    messagingSenderId: '375709920710',
    projectId: 'flutter-english-d72fb',
    storageBucket: 'flutter-english-d72fb.appspot.com',
    iosClientId: '375709920710-rs89a9j08k8qim31n8c50lpfgj8e19u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV5-RRqUd2_5wzwCYLKRpXMJDD5seWI-s',
    appId: '1:375709920710:ios:c064de22c3f77fa8ed16c7',
    messagingSenderId: '375709920710',
    projectId: 'flutter-english-d72fb',
    storageBucket: 'flutter-english-d72fb.appspot.com',
    iosClientId: '375709920710-3s3dhls63uv8oebvf1bddcr2n8d81jeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEnglish.RunnerTests',
  );
}
